### ISSUE TITLE
Celery releases are not ordered historically, missing latest release

### ISSUE THREAD

**Issue by coagulant** [AllMyChanges/original.allmychanges.com#22]
http://allmychanges.com/p/python/celery/

Latest release is 3.1.16, but it's missing from history.
Releases from 2013 are above 2014 releases.
Removed releases 3.2

**Comment by svetlyak40wt** [comment]
This is because there isn't `changelog-3.1.rst` in https://github.com/celery/celery/tree/master/docs/history.

Probably I should add an interface so that changelog's moderator could mark some versions as having issues or delete them completely. Version 3.2 was discovered in october and it's source is `docs/whatsnew-3.2.rst`.

Celery has very complicated documentation. So probably we should change changelog's source to HTML version `http://celery.readthedocs.org/en/latest/changelog.html`. I'll check if parser will be able to handle it correctly.

**Comment by svetlyak40wt** [comment]
Нет, пока что парсер не справляется с http://celery.readthedocs.org/en/latest/changelog.html
В ближайшее время попробую с этим что-нибудь сделать.

**Comment by svetlyak40wt** [comment]
Now changelog is ok.
