### ISSUE TITLE
The release information for a particular package seems wrong

### ISSUE THREAD

**Issue by Wtower** [AllMyChanges/original.allmychanges.com#32]
The release information for https://allmychanges.com/p/javascript/ckeditor-dev/ is way different than https://github.com/ckeditor/ckeditor-dev/releases (which is right as ckeditor is indeed up to 4.4.7).

**Comment by svetlyak40wt** [comment]
First of all, https://github.com/ckeditor/ckeditor-dev/releases is not a real Releases, but only a git tags.

Secondly, our parser is pulling versions from plugins/codesnippet/lib/highlight/CHANGES.md which is wrong place, obviously.

To point our robot to a real changelog file, you have either add `plugins/` into a "Ignore these dirs and files" list, or to add `CHANGES.md` into a "Search in these dirs and files" list. The latter is preferred way, because in this case robot will check only that one file.

**Comment by svetlyak40wt** [comment]
I already fixed `ckeditor`, pointing it to the `CHANGES.md`. And deleted all wrong versions.
Please, note that because of it was added and tuned after that, our robot will send you all dicovered versions instead of latest one. This is not a bug in this case.

**Comment by Wtower** [comment]
Ok, now I understand. Thank you for your help.
