### ISSUE TITLE
Dancer2 release order is wrong

### ISSUE THREAD

**Issue by rleir** [AllMyChanges/original.allmychanges.com#42]
The release order is wrong here:
https://allmychanges.com/p/perl/Dancer2/#0.162000

Minor problem, probably blamed on Dancer2's release numbering, but maybe you could sort by date not number?? 
Thanks -- Rick

**Comment by rleir** [comment]
This issue is minor. Closed.

**Comment by svetlyak40wt** [comment]
Rick, thank you. You are right, this issue is caused by unusual numbering of Dancer2. Some other perl projects use such numbering too. May be in future I'll add a sorting by release or discovery dates, but that is not my priority. Because AllMyChanges is my pet-project, I have only limited amount of time to devote to it.
