### ISSUE TITLE
Please allow to add all repos of some org/individual

### ISSUE THREAD

**Issue by yurikoles** [AllMyChanges/original.allmychanges.com#61]
I mean in one call, for example I want to add all repos under https://github.com/apple.

**Comment by svetlyak40wt** [comment]
In many cases, it is not enough just to paste and URL. Sometimes you need to tune the parser.

For example, [you've complained](https://github.com/AllMyChanges/allmychanges.com/issues/60) that there is the problem with Kubernetes's changelog. Right. This is because Allmychanges automatically has chosen a GitHub Releases as the source. And you need manually say it to search `CHANGLOG.*\.md` files in the repository.

That is why I think adding repositories in the batch mode is inappropriate.

**Comment by svetlyak40wt** [comment]
Actually, the more requested feature is ability to add repositories you are "watching" on the github. But there is same problem with them.

**Comment by yurikoles** [comment]
@svetlyak40wt how about batch/background processing? As I see now if user left processing page wanted repo will not be added?

**Comment by svetlyak40wt** [comment]
Yeah, if you didn't tuned and saved the result, it will be lost.
