### ISSUE TITLE
Infinite "Wainting in Queue" when adding new URL

### ISSUE THREAD

**Issue by vmignot** [AllMyChanges/original.allmychanges.com#63]
Hi,

I've been trying to add the following site : https://gitlab.com/gitlab-org/gitlab-ce

It gets stuck step "Waiting in the queue"

Thanks in advance, very good product :-)

**Comment by svetlyak40wt** [comment]
Probably somebody's request was processed and that repository was big.

Anyway, please, don't try to add a gitlab's repository to allmychanges, because it is huge and eats too many traffic and CPU. In such cases it is better to give a direct link to the changelog file, for example:

https://gitlab.com/gitlab-org/gitlab-ce/raw/master/CHANGELOG.md

Actually, there is already GitLab Community Edition's changelog. Just subscribe on it:

https://allmychanges.com/p/soft/GitLab%20Community%20Edition/

**Comment by vmignot** [comment]
Hi, thanks for the quick reply!

The changelog on AllMyChanges for gitlab-ce is out of date: the current version is 10.5.3 (2018-03-01).

I tried to submit a report about this on the page, but it seams broken (the request to https://allmychanges.com/v1/issues/ is giving a 500 error)

**Comment by svetlyak40wt** [comment]
Yeah, I've fixed the link to the changelog today, previously data was taken from CHANGELOG, but maintainers renamed it into the CHANGELOG.md. Parser need some time to update the project on AllMyChanges.

**Comment by svetlyak40wt** [comment]
AllMyChanges a little bit abandoned nowadays because I'm too busy at my day job and don't see much interest in AllMyChanges from the community :(

Maybe I'll rewrite it from Python to Common Lisp someday and it will make this project more interesting to develop and support.

**Comment by vmignot** [comment]
Thanks! I've followed this one!
